### ISSUE TITLE
EfCore 2.1+ ValueConverter

### ISSUE THREAD

**Issue by SeriousM** [microknights/Collections#1]
I just read your readme and found your call for help.

There is a way to convert a efcore model property on the fly without a backing field by using a value converter: https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#the-valueconverter-class

Please have a read and update the readme yourself if this is the answer to your question.

Have a nice day!

**Comment by microknights** [comment]
yes, forgot all about that question. Thanks for the update 👍
